2024-03-24 13:57:48,060 INFO    MainThread:14776 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-24 13:57:48,061 INFO    MainThread:14776 [wandb_setup.py:_flush():76] Configure stats pid to 14776
2024-03-24 13:57:48,062 INFO    MainThread:14776 [wandb_setup.py:_flush():76] Loading settings from C:\Users\raul\.config\wandb\settings
2024-03-24 13:57:48,062 INFO    MainThread:14776 [wandb_setup.py:_flush():76] Loading settings from C:\Users\raul\Universidad Pontificia Comillas\Javier Álvarez Martínez - MachineLoooorning\wandb\settings
2024-03-24 13:57:48,062 INFO    MainThread:14776 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-24 13:57:48,063 INFO    MainThread:14776 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-24 13:57:48,065 INFO    MainThread:14776 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'DeepLearning\\mainTraining.py', 'program_abspath': 'C:\\Users\\raul\\Universidad Pontificia Comillas\\Javier Álvarez Martínez - MachineLoooorning\\DeepLearning\\mainTraining.py', 'program': 'C:\\Users\\raul\\Universidad Pontificia Comillas\\Javier Álvarez Martínez - MachineLoooorning\\DeepLearning\\mainTraining.py'}
2024-03-24 13:57:48,065 INFO    MainThread:14776 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-03-24 13:57:48,066 INFO    MainThread:14776 [wandb_init.py:_log_setup():526] Logging user logs to C:\Users\raul\Universidad Pontificia Comillas\Javier Álvarez Martínez - MachineLoooorning\wandb\run-20240324_135748-5gb6399l\logs\debug.log
2024-03-24 13:57:48,066 INFO    MainThread:14776 [wandb_init.py:_log_setup():527] Logging internal logs to C:\Users\raul\Universidad Pontificia Comillas\Javier Álvarez Martínez - MachineLoooorning\wandb\run-20240324_135748-5gb6399l\logs\debug-internal.log
2024-03-24 13:57:48,067 INFO    MainThread:14776 [wandb_init.py:init():566] calling init triggers
2024-03-24 13:57:48,067 INFO    MainThread:14776 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-24 13:57:48,067 INFO    MainThread:14776 [wandb_init.py:init():616] starting backend
2024-03-24 13:57:48,067 INFO    MainThread:14776 [wandb_init.py:init():620] setting up manager
2024-03-24 13:57:48,086 INFO    MainThread:14776 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-24 13:57:48,092 INFO    MainThread:14776 [wandb_init.py:init():628] backend started and connected
2024-03-24 13:57:48,117 INFO    MainThread:14776 [wandb_init.py:init():720] updated telemetry
2024-03-24 13:57:48,121 INFO    MainThread:14776 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-24 13:57:49,744 ERROR   MainThread:14776 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-24 13:57:51,107 ERROR   MainThread:14776 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\raul\.conda\envs\noestructurados\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-24 13:57:53,102 WARNING MsgRouterThr:14776 [router.py:message_loop():77] message_loop has been closed
